spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/walmartprep
    username: adiivats
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate # Flyway handles schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: YOUR_JWT_SECRET_HERE
  expiration: 3600000 # 1 hour
  refresh-expiration: 604800000 # 7 days

gemini:
  api:
    key: YOUR_API_KEY_HERE

judge0:
  api:
    key: YOUR_JUDGE0_API_KEY_HERE
